### ISSUE TITLE
Recent updates to support ZSH shell break script for Bash shell

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-setup#3]
Need to revert back to the previous `sed` usage when carrying out string replacements, or introduce a means of detecting the ZSH shell and changing the usage depending on the shell being used.

**Comment by davetgreen** [comment]
This revert has already happened.

What is now needed is a solution that works for vanilla Bash shall, as well as the ZSH and possibly even Bourne shells for maximum compatibility.

**Comment by mwtsn** [comment]
@davetgreen now that the theme should reference the `kapow` namespace, there is less to do with this script.

**Comment by davetgreen** [comment]
@mwtsn I've just installed ZSH shell to see if there's any issues with the script, and I think I might have inadvertantly fixed this problem with my general updates?

Could you do me a favour when you get 5 and pull down the script into a test folder, `chmod a+x kapow.sh` and then run this?

`/kapow.sh develop stark-industries "Stark Industries" "Tony Stark" tony@starkindustries.com www.starkindustries.com`

I've just run this now and it all works! Not a sign of `My Project` anywhere!

I think it's the pointer to local bash at the very top of the file that was the solution. Without it, your ZSH terminal is using it's own thing.

**Comment by davetgreen** [comment]
yo @nervewax, are you on a windows laptop? If so, do you use a regular shell or a *nix based shell?

**Comment by nervewax** [comment]
@davetgreen I'm on mac, but I have a windows laptop if you want me to try it?

**Comment by davetgreen** [comment]
@nervemac that's cool man, if your primary dev machine runs OSX then I don't need to worry. 👌

**Comment by mwtsn** [comment]
@davetgreen I'm afraid this doesn't work with my shell still.

**Comment by davetgreen** [comment]
@mwtsn Potential fix is on `develop` branch. Fingers crossed!

**Comment by davetgreen** [comment]
Closing as recent fix has resolved issues with string replacement.
